module.exports = `
  type User {
    _id: ID!
    username: String!
    password: String!
    displayName: String
    email: String
    role: String!
    defaultWaterGoal: Int
    defaultSupplementJsons: [String]
  }

  enum RoleType {
    ADMIN,
    COACH,
    USER
  }

  type Auth {
    user: User
    token: String
  }

  extend type Query {
    users: [User]
    user(username: String!): User
    me: User
  }

  extend type Mutation {
    createUser(
      username: String!
      password: String!
      displayName: String
      email: String!
    ): Auth
    updateUser(
      username: String
      displayName: String
      email: String
      defaultWaterGoal: Int
      defaultSupplementJsons: [String]
    ): User
    editUser(
      _id: ID!
      username: String
      password: String
      displayName: String
      email: String
      defaultWaterGoal: Int
      defaultSupplementJsons: [String]
    ): User
    login(username: String!, password: String): Auth
    changePassword(oldPass: String!, newPass: String!): Boolean
    changeRole(userId: ID!, role: RoleType!): User
  }
`